### ISSUE TITLE
Song information doesn't change right away

### ISSUE THREAD

**Issue by teamreflect** [PtrBld/MMM-Scrobbler#10]
I am using Raspotify (https://github.com/dtcooper/raspotify} to stream on my Raspberry Pi, there is an issue that when I run Raspotify on the background while I run Scrobbler the song information doesn't change right away, and it takes around 50 secs .Do you think there is a way around this?

Thanks in advance.

**Comment by PtrBld** [comment]
Hi teamreflect,

when using scrobbler there will allways be some delay. So this is by design. 
Sorry
