### ISSUE TITLE
Module stops working when API key is used elsewhere? 

### ISSUE THREAD

**Issue by akraus53** [PtrBld/MMM-Scrobbler#17]
I wrote a skript to scrobble from my youtube music history ("off site", so not on the phone/pc/google home) and as soon as i use the script it stops showing the album art on the MagicMirror :(

**Comment by akraus53** [comment]
UPDATE: I fixed this, you need a separate API key for every tool you write. Leaving this open tho, hoping it will help somebody else

**Comment by PtrBld** [comment]
Ok, thanks for the update! I will close this and add it to the readme.
