### ISSUE TITLE
How to increase size of album art ?

### ISSUE THREAD

**Issue by maxencekyz** [PtrBld/MMM-Scrobbler#18]
Hello,

I really appreciate your effort for the development of MMM-Scrobbler, that's amazing !!!

However, I've got an issue regarding the size of the album artwork + titles.
It's very small. I tried many things in .css to make it bigger but didn't work.

See picture for a better understanding :
https://imgur.com/a/c6nUfhW

Any idea ?
https://github.com/PtrBld/MMM-Scrobbler/blob/master/MMM-Scrobbler.css

Really really really appreciate your help,

Thanks :))))
And have a nice day !
- Maxence
@joenas @phrogg @PtrBld @gerardcuadras-zz

**Comment by PtrBld** [comment]
Hi, 
if you want to have the module in the middle lane you should first of all change the ``position`` to ``middle_center`` or something similar (see https://docs.magicmirror.builders/modules/configuration.html) in your config. 
Then I would suggest you try to adjust the width of css classes ``.player`` and ``.album-art`` to be bigger.

Hope this helps.

**Comment by maxencekyz** [comment]
Hello @PtrBld ,
So quick to reply back, thank you so much !!
I tried this already but unfortunately nothing changed.

Here is my custom.css config :

>   .meta .track-name {
    color: #ffffff;
text-align: center;
  }
  .meta .artist-name {
    color: #ffffff;
text-align: center;
  }
.meta .album-name {
    color: #ffffff;
text-align: center;
  }
.player{
width:200px;
}
.album-art{
  margin-right:30px;
  width:300%;
  }
  
  
Do you have any custom.css code that works on your side so I can copy/paste and try ?

Thanks for your support,
I love this communityyyy

**Comment by maxencekyz** [comment]
Find the issue !

Go find
`img src='"+ this.songData.image +"' width='200'`
in the MMM-Scrobbler.js and changed it to

> img src='"+ this.songData.image +"' width='450' height='450'

**Comment by maxencekyz** [comment]
**Now, there is the last problem**. When **increased the size of album** cover, the **quality remains the same**. It's awful.
Any idea to solve this ?

Let me show you the picture from LAST.FM :
![image](https://user-images.githubusercontent.com/80335419/110765659-b1fddc00-8254-11eb-8d46-312de8b51091.png)

And the picture on Magic Mirror with your module :
![image](https://user-images.githubusercontent.com/80335419/110765786-d1950480-8254-11eb-93e9-9900adcfb983.png)

Any idea to have the best quality ?
Thanks per advance,

PS : My PayPal is ready for anyone who can help me 🥇 
@PtrBld @joenas @phrogg @gerardcuadras-zz

**Comment by joenas** [comment]
> **Now, there is the last problem**. When **increased the size of album** cover, the **quality remains the same**. It's awful.
> Any idea to solve this ?

Hey. You could have a look at Last.FMs API and see if you can get another resolution with query parameters perhaps? Code here: https://github.com/PtrBld/MMM-Scrobbler/blob/master/MMM-Scrobbler.js#L78

Now I'm not a maintainer of this project, just a contributor, so I would appreciate if you could stop tagging me 😄  👍  
Good luck!

**Comment by maxencekyz** [comment]
Hello Joenas,

So sorry haha
Ok, thanks for the tip, i will do my own research there.

Have a great day mate !
This subject is closed.

**Comment by PtrBld** [comment]
If I remeber correctly the API returns an array of images. See:
[``self.songData = {title:a.name,artist:a.artist["#text"],album:a.album["#text"],image:a.image[2]["#text"], playing: nowplaying};``](https://github.com/PtrBld/MMM-Scrobbler/blob/e2280f653a7a563274ab3de26949c3eb7ee01f66/MMM-Scrobbler.js#L93)

We use ``a.image[2]`` atm. You could try to use another image from this array. This would be the only solution in my opinion.
