### ISSUE TITLE
Clarification on DelayCount - DelayInterval

### ISSUE THREAD

**Issue by maxencekyz** [PtrBld/MMM-Scrobbler#19]
Hello @PtrBld ,

Module works perfectly when I turn ON my magic mirror.
**However, if i'm not listening to the music during all day long**. And I **come back home**, starting the music again, the **module is always showing : "Not playing..."**

I'm sure the problem comes from these 2 criterias "DelayCount - DelayInterval"
Could you please clarify these ? It's not clear for me.

**DelayCount : "How often should we try to retrieve a song if not listening"**
What value should I put then ? Maybe `delayCount : 1000000000000` ? So I could not listen to music for few days and it will works perfectly when i will need it, right ?

**DelayInterval : " Time interval to search for new song if the 5 times not listening is received. Set this to the same number as updateInterval to ignore this option"**
What value should I put to avoid problem as well ? 

This is my config :
```
//time interval to search for new song (every 2 seconds)
updateInterval: 2 * 1000,
//how often should we try to retrieve a song if not listening
delayCount: 10,
//time interval to search for new song if the 5 times not listening is received.
//set this to the same number as updateInterval to ignore this option	
delayInterval: 10*1000,
```

Thank you ! :)

**Comment by PtrBld** [comment]
Hi, 
sorry for the confusion.
delayCount is the number of times a update is tried using updateInterval with no success (no title is playing) before we switch to the longer delayInterval.
This distinction is made to reduce API calls during times when no music is played.
If you want to ignore this you can just set updateInterval and delayInterval to the same value and see if it is working then...

If not just let me know.
