### ISSUE TITLE
Module messes up formatting of the rest of the display

### ISSUE THREAD

**Issue by pyrosmiley** [PtrBld/MMM-Scrobbler#8]
Talk about timing -- I was going to spend today trying to do exactly what you just did with the most recent update! Was very excited. Unfortunately, whether or not the `alignment:` config option is set (and regardless of the value, it seems), the module now causes all the others to overlap on the right side of the screen? I'll attach pictures. I'm sure it's not a big issue to fix, but I've tried it with and without MMM-Scrobbler just to make sure.

Either way, thanks so much for putting this module together -- it's exactly what I wanted for my display! 

![img_4219](https://user-images.githubusercontent.com/11056798/30384266-76b5b998-9869-11e7-859b-7327748e95e3.JPG)
![img_4220](https://user-images.githubusercontent.com/11056798/30384270-7a04fe2e-9869-11e7-9a4c-755ef6bbeaca.JPG)

**Comment by PtrBld** [comment]
Oh I see! It is a naming problem. Sry I did not test the changes, yet. Will be fix soon

**Comment by PtrBld** [comment]
Ok should be fixed

**Comment by pyrosmiley** [comment]
Works perfectly for me! Big thanks.
